Peibankongjian/Controllers/RenAccountController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using SkyDal;
using SkyCommon;
using SkyService;

namespace Peibankongjian.Controllers
{
    public class RenAccountController : Controller
    {
        private UnitOfWork unitOfwork = new UnitOfWork();

        public ActionResult Login()
        {
            ViewBag.msg = "";

            return View();
        }


        [HttpPost]
        public ActionResult Login(FormCollection fc)
        {
            System.Web.HttpContext.Current.Session["renname"] = "";
            string username = fc["UserName"];
            string password = CommonTools.ToMd5(fc["Password"].ToString());

            var rens = unitOfwork.rensRepository.Get(filter: u => u.RenPhone == username && u.RenPassword == password);


            if (rens.Count() > 0)
            {
                if (rens.First().Status)
                {
                    HttpCookie cookie = new HttpCookie("renname");
                    cookie.Value = username;
                    System.Web.HttpContext.Current.Response.Cookies.Add(cookie);

                    HttpCookie cookieid = new HttpCookie("renid");
                    cookieid.Value = rens.First().Id.ToString();
                    System.Web.HttpContext.Current.Response.Cookies.Add(cookieid);

                    System.Web.HttpContext.Current.Session["renid"] = rens.First().Id.ToString();
                    System.Web.HttpContext.Current.Session["renname"] = username;
                    System.Web.HttpContext.Current.Session["Vip"] = "false";
                    System.Web.HttpContext.Current.Session["Peibanshi"] = "false";
                    if (PeibanService.GetVipByRen(1,1,rens.First().Id))
                    {
                        System.Web.HttpContext.Current.Session["Vip"] = "true";
                    }
                    if (PeibanService.GetVipByRen(1, 2, rens.First().Id))
                    {
                        System.Web.HttpContext.Current.Session["Vip"] = "true";
                        System.Web.HttpContext.Current.Session["Peibanshi"] = "true";
                    }

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.msg = "此已经被禁用，不允许登陆";
                    return View();
                }
            }
            else
            {
                ViewBag.msg = "用户名或密码错误";
                return View();

            }
        }


        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Response.Cookies["renname"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["renid"].Expires = DateTime.Now.AddDays(-1);
            System.Web.HttpContext.Current.Session["renid"] = null;
            System.Web.HttpContext.Current.Session["renname"] = null;
            System.Web.HttpContext.Current.Session["Vip"] = null;
            System.Web.HttpContext.Current.Session["Peibanshi"] = null;
            return View("Login");
        }
	}
}

Peibankongjian/Views/RenAccount/Login.cshtml
@{
    ViewBag.Title="陪伴空间";
}

<div class="container peiban-container">

    <div class="row">
        <div class="col-md-6">
            <h3 style="margin: 20px 0px 40px 0px;">登陆</h3>
            <div class="row">

                @if (!string.IsNullOrEmpty(ViewBag.msg))
                { 
                     <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>Warning!</strong> @Html.Raw(ViewBag.msg)
                </div>
                
                }
                
                @using (Html.BeginForm("Login", "RenAccount", FormMethod.Post, new { @class = "form-horizontal", @name = "LoginForm", @id = "LoginForm" }))
                {
                    <div class="form-group">
                       
                        <label class="control-label col-sm-2">手机账号</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="username" id="username" type="text" placeholder="请输入手机号" />
                        </div>
                    </div>

                    <div class="form-group">
                       
                        <label class="control-label col-sm-2">密码</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="password" id="password" type="password" placeholder="请输入密码" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-6 col-sm-offset-2">
                            @*<span class="pull-left"><a href="###">忘记密码？</a></span>*@
                            <button class="btn btn-success pull-right" type="submit">&nbsp;&nbsp;&nbsp;登陆&nbsp;&nbsp;&nbsp;</button>
                        </div>
                    </div>

                }

            </div>
           
        </div>
        <div class="col-md-6" style="margin-top: 80px;line-height:30px;">
            没有账号？扫描下方二维码注册账号<br /><br />
            <img src="/Resource/img/qrcode_peiban.jpg" class="image" />
            <br /><br />
            1、<strong>注册方式：</strong>点击个人中心=》注册账号 免费注册<br />
            2、<strong>忘记密码：</strong>请联系微信小助手：peibanshichengzhagn
            
        </div>
    </div>

</div>


@section BottomScripts {
    <script type="text/javascript">
       
    </script>
}